#! /usr/bin/env python3
import conway_life as life
import lifeutils

def test() :
    X, Y, start = lifeutils.readt("""\
..........
......x...
....xxx...
.....x....
..........
..........
..........
..........
..........
..........
""")

    end = [False] * X * Y
    p_cnt = [0]
    def callback(liter, count, lhash, f, fin) :
        assert p_cnt[0] == liter
        p_cnt[0] += 1
        assert fin == (liter == 100)

    res = life.run(X, Y, 1, 100, start, end, callback)

    s_end = lifeutils.savet(X, Y, end)
    print(s_end, end='')

    assert s_end == """\
..........
..x.......
.x.x......
.x..x.x...
.xxxxx.x..
.xx..xx...
....x.....
....x.....
..........
..........
"""

    assert res == 100

    print("Passed")


if __name__ == "__main__" :
    test()
